# Generated by Django 5.1.6 on 2025-03-04 15:31

from django.db import migrations #type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flashcard',
            new_name='User_Details',
        ),
    ]
